for name in ../../datasets/AID/AID_imgs//Port/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//RailwayStation/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Mountain/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//School/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Beach/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//MediumResidential/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Farmland/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Viaduct/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//StorageTanks/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Forest/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//SparseResidential/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Meadow/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Resort/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Playground/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Desert/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Church/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//BaseballField/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Bridge/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Square/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Center/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//DenseResidential/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Industrial/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Commercial/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Airport/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//BareLand/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//River/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Pond/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Parking/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Stadium/*.jpg; do     convert -resize 320x320\! $name $name; done
for name in ../../datasets/AID/AID_imgs//Park/*.jpg; do     convert -resize 320x320\! $name $name; done
